feat(RAIN-3): main window setup
oowliq/rain pull request #2
Opened 2024-02-22 22:47 UTC by oowliq

2024-02-22 22:56 UTC, dima-sheiko commented on components.json
> +		"components": "@shared/uiKit/components",
го просто ui, а не uiKit, не оч выглядит (да, я эстет)

2024-02-22 23:03 UTC, dima-sheiko commented on components.json
> +		"utils": "@shared/uiKit/utils"
мб сделаем в shared папку lib и туда будут идти все глобальные ютилзы? туда возможно можно и providers положить

2024-02-22 23:05 UTC, dima-sheiko requested changes
написал предложения

2024-02-23 05:34 UTC, oowliq commented on components.json
> +		"utils": "@shared/uiKit/utils"
Провайдеры должны находится в App

2024-02-23 05:39 UTC, oowliq commented on components.json
> +		"components": "@shared/uiKit/components",
https://github.com/oowliq/rain/pull/2/commits/b5143f25203e6a331d202e541072902a8c636940

2024-02-23 07:43 UTC, dima-sheiko approved these changes

2024-02-23 08:38 UTC, merged